services:
  db:
    image: postgres:latest
    container_name: quillkalam-local-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quillkalam
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quillkalam_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
